### ISSUE TITLE
Display categories

### ISSUE THREAD

**Issue by rclebsch** [pkohlernet/itc_005#9]
The categories must be visible for the users as they do not know which categories exist. 

In addition, it would be good to group brochures, manuals, etc to facilitate the search.

**Comment by legacarta** [comment]
El tema con las categorías sería: hacerlas visibles en los sub-menus (con un hyperlink) con acceso al contenido de la pagina

Para los Resources/documentos lo mismo, presentar un sub-menu fijo que envíe al contenido de la pagina. 
En efecto, es importante que se muestren como grupos de alguna forma. Creo que la gente va a utilizar menos el filtro en la parte de Resources.

En Reources, la idea es que se muestre una imagen -mediana-  que el sistema lea del archivo que hemos subido. Si está así la funcion, ok . Sino No vamos a crearla para que tengamos que cargar una imagen por cada documento porque ello será demasiado trabajo (crear una imagen para cada doc y subirla).

**Comment by pkohlernet** [comment]
Ok, me parece bien listar las categorías como sub-menúes a la izq y desde ahí también filtrar. 
Voy a agregar las categorías como sub-menú en business-contacts y resources.

http://74.208.109.84/app/
Andá a resources publicationas and downloads, vas a ver que "ITC model contract International Commercial Sale of Goods" tiene una imágen cargada. Cuando pasás el mouse sobre esa imagen hace zoom para poder verla bien.

**Comment by pkohlernet** [comment]
Business Contacts y resources generan dinámicamente submenús en base a las categorías con contenido. Al hacer click en esos submenús se dispara el filtro dentro la grilla.
Te agregué registros de test en ambas pantallas para que se van mejor el resultado final.
